# Generated by Django 3.2.9 on 2021-11-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_server', '0002_alter_game_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='game_id',
            new_name='game',
        ),
    ]
